### ISSUE TITLE
Can't initialize React adapter

### ISSUE THREAD

**Issue by drehimself** [inertiajs/inertia-react#20]
Hello,

I'm able to get the Vue adapter working with Laravel but when trying to use the React adapter I get the following error after running `npm run watch`:

 ERROR  Failed to compile with 1 errors

 error  in ./resources/js/app.js

Syntax Error: SyntaxError: /Users/Dre/code/playground-inertia-react/resources/js/app.js: Unexpected token (8:2)

```
   6 |
   7 | render(
>  8 |   <Inertia
     |   ^
   9 |     initialPage={JSON.parse(app.dataset.page)}
  10 |     resolveComponent={name => import(`@/Pages/${name}`).then(module => module.default)}
  11 |   />,
```

I noticed this warning too `inertia-react@0.1.0 requires a peer of react@^16.8.0 but none is installed. You must install peer dependencies yourself.`. I tried to install react manually with `npm install react` but still get the same error above.

npm version: 6.9.0
node version: v10.3.0

Thanks!

**Comment by MichaelDeBoey** [comment]
You should install `react-dom` too, just like you would do in another `react` SPA.

**Comment by drehimself** [comment]
I tried manually installing `react-dom` too, same error.

Here is my example repo: https://github.com/drehimself/playground-inertia-react

**Comment by MichaelDeBoey** [comment]
@drehimself From looking at your example repo,  you don't have an `resources/js/Pages` folder.
This folder should also contain the `Event.vue` component, otherwise it would keep failing.

Can't test this out right now since I'm on the train so can't do any `composer install` and `npm install`.
If this still doesn't work, let me know and I'll take a look later today. 🙂

**Comment by drehimself** [comment]
Added `Pages` and `Shared` folder with Layout. Same issue.

No rush. Appreciate you looking into it! I'm sure it's something minor, haha.

**Comment by MichaelDeBoey** [comment]
Code seems good now, but will take a look later today 😉

**Comment by MichaelDeBoey** [comment]
Hi @drehimself!

Since we changed a lot of the code (both in the core & in the adapters) and so did our public API a bit, can you try again setting up a project following our README please?

If you still encounter problems be my guest to come back to me, but right now it's very hard for me to see what was possibly wrong, since we're working with Github dependencies instead of real semver ones.

`0.x` releases are on their way, but have to struggle a bit with finding out bugs until then 😉

**Comment by drehimself** [comment]
Fixed it after some googling / stackoverflowing!

Add this line to `.babelrc` file:

`"presets": ["@babel/preset-react"]`

Install packages:

`npm install --save @babel/preset-react react react-dom`

Example repo updated: https://github.com/drehimself/playground-inertia-react

Let me know if you want me to add to readme and I'll submit a PR.

**Comment by MichaelDeBoey** [comment]
I see what went wrong now after your explanation how you fixed it.

You should have used `mix.react` instead of `mix.js` in your [`webpack.config.js`](https://github.com/drehimself/playground-inertia-react/blob/master/webpack.mix.js#L14), like we suggest in our [README](https://github.com/inertiajs/inertia-react#setting-up-webpack)

```diff
  const mix = require('laravel-mix')
  const path = require('path')

  mix
-   .js('resources/js/app.js', 'public/js')
+   .react('resources/js/app.js', 'public/js')
    .sass('resources/sass/app.scss', 'public/css')
    .webpackConfig({
      output: { chunkFilename: 'js/[name].[contenthash].js' },
      resolve: {
        alias: {
          '@': path.resolve('resources/js'),
        },
      },
    })
```

**Comment by drehimself** [comment]
I knew I missed something! 

I assumed the `webpackConfig` function was the only thing that changed (like in vue).

Thank you for the help!

**Comment by MichaelDeBoey** [comment]
Happy to help 🙂
